
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost/pharmaerp}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

