
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost/pharmaerp?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB