
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmaerp
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  #        generate_statistics: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  mail:
    host: smtp.googlemail.com
    port: 587
    username: mailserver@dkspacejsc.com
    password: RnWXg7YVquWG8rP@
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true