
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost/pharmaerp}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    DKSPACE.PhamarERP: DEBUG